language: ruby
rvm:
- 2.3.3
jdk:
- oraclejdk8
env:
  - URL=https://github.com/redpen-cc/redpen/releases/download/redpen-1.10.1
before_script:
  - hostname
  - whoami
  - openssl aes-256-cbc -K $encrypted_2b6eab55118f_key -iv $encrypted_2b6eab55118f_iv -in github_deploy_key.enc -out id_rsa -md md5
  - mv id_rsa ~/.ssh/
  - eval $(ssh-agent -s)
  - ls -la ~/.ssh/
  - cat ~/.ssh/config
  - cat ~/.ssh/known_hosts
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e 'ssh.github.com,192.30.253.113 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
#  - sed -i '/github.com/d' ~/.ssh/known_hosts
  - chmod 700 ~/.ssh
  - chmod 600 ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/config
  - ls -la ~/.ssh/
  - cat ~/.ssh/config
  - cat ~/.ssh/known_hosts
  - ssh-add id_rsa
  - ssh -o 'StrictHostKeyChecking no' github.com
  - git config --global --list
  - git config --global user.email "hirofumi-yoshida@science.co.jp"
  - git config --global user.name "hs-yoshida"
  - git config --global --list
  - git clone git@github.com:hs-yoshida/connect.git
  - git checkout master
#install:
#  - wget $URL/redpen-1.10.1.tar.gz
#  - tar xvf redpen-1.10.1.tar.gz
#  - export PATH=$PATH:$PWD/redpen-distribution-1.10.1/bin
script:
#  - redpen -f asciidoc source/*.adoc
   - echo 'hello world' > helloworld.txt
after_success:
  - git fetch git@github.com:hs-yoshida/connect.git
after_success:
  - hostname
  - whoami
  - openssl aes-256-cbc -K $encrypted_2b6eab55118f_key -iv $encrypted_2b6eab55118f_iv -in github_deploy.enc -out ~/.ssh/id_rsa -md md5
  - mv id_rsa ~/.ssh/
  - ls -la ~/.ssh/
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - chmod 700 ~/.ssh 
  - chmod 600 ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/known_hosts
  - cat ~/.ssh/config
  - cat ~/.ssh/known_hosts
  - git config --global --list
  - git config --global user.email "hirofumi-yoshida@science.co.jp"
  - git config --global user.name "hs-yoshida"
  - git config --global --list
  - git clone git@github.com:hs-yoshida/connect.git
  - git checkout master
  - git checkout -b gh-pages
#  - cd master
  - git add --all
  - git commit -m "by Travis CI (JOB $TRAVIS_JOB_NUMBER)"
#  - git push origin master
  - git push git@github.com:hs-yoshida/connect.git gh-pages --force
notifications:
  slack: humanscience-ds:bKpIKhcfWAAAugmKF5t7AF4B
