language: ruby
rvm:
- 2.3.3
jdk:
- oraclejdk8
env:
  - URL=https://github.com/redpen-cc/redpen/releases/download/redpen-1.10.1
before_script:
  - openssl aes-256-cbc -K $encrypted_2b6eab55118f_key -iv $encrypted_2b6eab55118f_iv -in github_deploy_key.enc -out github_deploy_key -md md5
  - mv github_deploy_key ~/.ssh/
  - ls -la ~/.ssh/
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config 
  - chmod 600 ~/.ssh/github_deploy_key
  - chmod 600 ~/.ssh/config
#  - ls -la ~/.ssh/
#  - eval $(ssh-agent -s)
#  - ssh-keygen -R github.com
#  - ssh -o 'StrictHostKeyChecking no' github.com 
#install:
#  - wget $URL/redpen-1.10.1.tar.gz
#  - tar xvf redpen-1.10.1.tar.gz
#  - export PATH=$PATH:$PWD/redpen-distribution-1.10.1/bin
script:
#  - redpen -f asciidoc source/*.adoc
   - echo 'hello world'
after_success:
  - git fetch git@github.com:hs-yoshida/connecn.git
after_success:
  - openssl aes-256-cbc -K $encrypted_2b6eab55118f_key -iv $encrypted_2b6eab55118f_iv -in travis_key.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email "hirofumi-yoshida@science.co.jp"
  - git config --global user.name "hs-yoshida"
  - git clone git@github.com:hs-yoshida/connect.git
#  - cd master
  - git add --all
  - git commit -m "by Travis CI (JOB $TRAVIS_JOB_NUMBER)"
  - git push origin master
  - git push git@github.com:hs-yoshida/connect.git gh-pages --force
notifications:
  slack: humanscience-ds:bKpIKhcfWAAAugmKF5t7AF4B
